name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build backend image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend ./expenseiq/backend

    - name: Build frontend image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend ./expenseiq/frontend

    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          docker stop backend || true
          docker stop frontend || true
          docker rm backend || true
          docker rm frontend || true
          docker run -d -p 5000:5000 --name backend ${{ secrets.DOCKERHUB_USERNAME }}/backend
          docker run -d -p 3000:3000 --name frontend ${{ secrets.DOCKERHUB_USERNAME }}/frontend
